### ISSUE TITLE
Readme doesn't line up with actual commands

### ISSUE THREAD

**Issue by opencoca** [dlemstra/magick-wasm-docs#3]
I've noticed a discrepancy between the commands listed in our `README.md` and what's actually in our `package.json`. This could lead to confusion for developers trying to set up or maintain the project. Below, I've outlined the discrepancies:

### Details in `package.json`

```markdown
"dev": "vite",
"build": "run-p type-check \"build-only {@}\" && cpy ./dist/index.html . --rename 404.html",
"preview": "vite preview",
"build-only": "vite build",
"type-check": "vue-tsc --build --force",
"lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore"
```

#### Project setup
```markdown
npm install
```

#### Compiles and hot-reloads for development
```markdown
npm run serve
```

#### Compiles and minifies for production
```markdown
npm run build
```

#### Lints and fixes files
```markdown
npm run lint
```

### Suggested Action

Could we update the README to accurately reflect the commands in the `package.json`? This will help ensure everyone is on the same page and make the setup process smoother for new contributors. At the moment only build and lint are in the readme and serve will result in an error message:

```
npm ERR! Missing script: "serve"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2024-04-29T10_02_47_522Z-debug-0.log
```

Thank you!

**Comment by dlemstra** [comment]
I have updated the readme, thanks for pointing this out. Next time feel free to submit a PR for this.
